Add HW-12
irynaa-semchuk/HW pull request #14
Opened 2021-06-07 15:18 UTC by irynaa-semchuk

"Flask Intro"

2021-06-07 15:21 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW12 "Flask Intro" Ira Semchuk](https://trello.com/c/30apKXHN/273-hw12-flask-intro-ira-semchuk)

2021-07-09 19:21 UTC, dimigor requested changes

2021-07-09 19:21 UTC, dimigor commented on HW_12/app.py
> +        return render_template('calc.html', result="Data was entered incorrectly")
щоб не писати купу цих ретурнів, зроби мапу з назвою операції та символом
та через функцію eval() отримуй результат

2021-08-19 16:09 UTC, dimigor approved these changes

2021-09-25 19:21 UTC, merged