HW-13(11)
irynaa-semchuk/HW pull request #15
Opened 2021-06-12 18:40 UTC by irynaa-semchuk

2021-06-12 18:41 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW13(11) "Flask Practice" Ira Semchuk](https://trello.com/c/L0TsXjRf/286-hw1311-flask-practice-ira-semchuk)

2021-07-20 19:30 UTC, dimigor requested changes

2021-07-20 19:30 UTC, dimigor commented on HW_13/app.py
> +    weather = []
розділи логіку на функції
prepare_request
request
parse_response

2021-07-20 19:30 UTC, dimigor commented on HW_13/.env
> +WEATHER_API_HOST="community-open-weather-map.p.rapidapi.com"
незабувай про ендлайни

2021-11-26 16:16 UTC, merged