Add HW-14
irynaa-semchuk/HW pull request #16
Opened 2021-06-14 20:18 UTC by irynaa-semchuk

Add HW-14(12) "Flask and Rest"

2021-06-14 20:21 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW14(12) "Flask and Rest" Ira Semchuk](https://trello.com/c/nJypFdMR/309-hw1412-flask-and-rest-ira-semchuk)

2021-08-06 16:42 UTC, dimigor requested changes

2021-08-06 16:42 UTC, dimigor commented on HW_12/app.py
> +        return render_template('calc.html', x=x, y=y, result=x / y, symbol="/")
використай дікт з мапінгом операцій, та функцію eval

2021-08-06 16:42 UTC, dimigor commented on HW_12/docker/python/Dockerfile
> +CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
endline

2021-11-26 16:16 UTC, merged