Add HW-15(13)
irynaa-semchuk/HW pull request #17
Opened 2021-06-19 19:06 UTC by irynaa-semchuk

2021-06-19 19:07 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW15 "Flask Practice" Ira Semchuk](https://trello.com/c/twZqR3O2/329-hw15-flask-practice-ira-semchuk)

2021-08-19 16:08 UTC, dimigor requested changes

2021-08-19 16:08 UTC, dimigor commented on HW_15/app.py
> +    # db.create_all()
чому закоментовано?

2021-08-19 16:08 UTC, dimigor commented on HW_15/config.py
> +    ]
одна порожня стрічка має бути вкінці кожного файлу

2021-08-19 16:08 UTC, dimigor commented on HW_15/models/Todo.py
> +from . import db
не використовуй в шляхах крапки

2021-08-19 16:08 UTC, dimigor commented on HW_15/routes/todo.py
> +api.add_resource(Todo, '/todos/<int:todo_id>')
добав ресурси в основному файлі

2021-11-26 16:16 UTC, merged