Add HW-16
irynaa-semchuk/HW pull request #18
Opened 2021-06-22 22:17 UTC by irynaa-semchuk

Lecture #16 "Flask and SQLAclhemy"

2021-06-22 22:17 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW16 "Flask and SQLAclhemy" Ira Semchuk](https://trello.com/c/g2EGnBYm/339-hw16-flask-and-sqlaclhemy-ira-semchuk)

2021-08-19 18:36 UTC, dimigor requested changes

2021-08-19 18:36 UTC, dimigor commented on HW_16/routes/blog.py
> +            img=data.get('img')
почитай про анпакінг дікта

2021-08-19 18:36 UTC, dimigor commented on HW_16/routes/blog.py
> +        # articles = articles.filter(Article.title.startswith('A'))
не коміть закоменчений код

2021-08-19 18:36 UTC, dimigor commented on HW_16/routes/blog.py
> +        serialized_articles = []
використай ліст компрехеншинс

2021-11-26 16:16 UTC, merged