Add HW-18
irynaa-semchuk/HW pull request #20
Opened 2021-06-30 18:08 UTC by irynaa-semchuk

Lecture #18 "Regular expressions"

2021-06-30 18:27 UTC, irynaa-semchuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW18 "Regular expressions" Ira Semchuk](https://trello.com/c/LLJJv1zg/377-hw18-regular-expressions-ira-semchuk)

2021-08-19 18:25 UTC, dimigor requested changes

2021-08-19 18:25 UTC, dimigor commented on HW_18/parsing_site.py
> +    print(r)
в кінці має бути порожня стрічка

2021-08-19 18:25 UTC, dimigor commented on HW_18/parsing_site.py
> +data = requests.get(
обгорни це все в функцію

2021-08-19 18:25 UTC, dimigor commented on HW_18/parsing_site.py
> +    print(r)
повертай резульат, а не прінтуй

2021-11-26 16:17 UTC, merged